[package]
name = "bevy-postprocess-test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.0-rc.3", features = ["file_watcher"] }

[[example]]
name = "render_to_texture"
path = "examples/render_to_texture.rs"

[[example]]
name = "text2d"
path = "examples/text2d.rs"
